### ISSUE TITLE
add a firmware update progress bar

### ISSUE THREAD

**Issue by 1TekPro** [prampec/IotWebConf#21]
@prampec  I wrote some code to add a progress bar when using an OLED display on an esp32. How do I go about adding it so it displays when a user clicks "upload"?
I'm guessing somewhere between:
`if(upload.status == UPLOAD_FILE_START){`
`if(Update.end(true)){ `
Can this be done by calling it from the main sketch?

**Comment by prampec** [comment]
While HTTPUpdateServer shouldn't be part of the IotWebConf code, currently it is on ESP32 (because it does hot have an official implementation for ESP32).
But, yes. If you inspect the code, you can see, that in debug mode the software writes some dots to the serial console, when an upload chunk is received (UPLOAD_FILE_WRITE).
At that point you might able operate with HTTPUpload.currentSize and HTTPUpload.totalSize to display your progress bar. (I'm not sure tho, HTTPUpdateServer is not my code.)

**Comment by 1TekPro** [comment]
@prampec  I am really struggling with this.
I have tried both HTTPUpload,currentSize and upload.currentSize, both error.
If it prints dot, it should print some math...
Serial.printf("Progress: %u%%\r", (upload.currentSize / (upload.totalSize / 100)));

Please, any help would be greatly apprciated.
