### ISSUE TITLE
How to reset every config?

### ISSUE THREAD

**Issue by Geraldo-Neto** [prampec/IotWebConf#58]
Simple question: how do I reset every single config to its defaults ?

**Comment by syrinxtech** [comment]
I've had to do this several times.  You just create a short routine to write 0's to the first X bytes of EEPROM, where X = size of the configuration.  If you're not sure, you could always write 1K worth, and that should work fine.

I'm looking for a way to do this to individual parameters instead of the whole EEPROM configuration.

**Comment by mangtronix** [comment]
Here's a sketch that clears the whole EEPROM area. Useful for obliterating the stored config before reprogramming https://github.com/mangtronix/InternetOfOurThings/blob/master/eeprom_clear_esp/eeprom_clear_esp.ino

**Comment by prampec** [comment]
Check #176, but basically you can e.g. use:
iotWebConf.getSystemParameterGroup()->applyDefaultValue();

Will be enabled with version v3.0.2
