### ISSUE TITLE
Where is stored img from example #10 CustomHTML

### ISSUE THREAD

**Issue by BrtVn** [prampec/IotWebConf#72]
Hello,

great work, thanks!  

Where I can store imgs to be loaded at AP mode (e.g. without internet connection)?

> const char CUSTOMHTML_BODY_INNER[] PROGMEM = "<div><img src='data:image/png;base64, iVBORw0KGgoAAAANSUhEUg........

**Comment by feder-ico** [comment]
The image is stored on the device since it is harcoded on the source code.
The string you see on the <img> tag iVBORw0KGgoAAAANSUhEUg... is the image itself
You can convert a PNG to base64 and replace the text so you are replacing the image.

You can find a cool online tool here: https://www.base64-image.de/
